= Jin Shibo - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Tasketch

---

== Overview

My teammates and I developed Tasketch for those who need to manage their time by allocating time for each daily task. More importantly, our Tasketch is optimized for those who prefer to use a desktop app and work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI)

== Summary of contributions

* *Major enhancement*: I have added *the reminder feature* to our Tasketch.
** What it does: Sometimes student tend to forget important deadline of their tasks or start time of their CCA events and etc. The reminder will show a list of tasks in time order for them to conveniently view what tasks are coming soon so that they will know what to prepare first.
** Justification: For busy university students, it is almost impossible for them to remember every start time or deadlines of their activities. A reminder is a common requirement of them to easily view these time in order. This feature significantly improves the users' using experience by meeting this requirement.
** Highlights: This feature implement a very useful method sort() in model API which can be used to implement other features.


* *Minor enhancement*: I made an enhancement to the list command of the previous version. In the previous version, list command can only list all the tasks in the storage. After enhancement, it support the usage like *list td* to list all the tasks of today so that user will know what need to be done today easily. It also support *list [DATE]*, which show a list of tasks on the specified date.


* *Code contributed*: [https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=&sort=displayName&since=2019-02-10&until=2019-04-01&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false&tabAuthor=BrittonAlone&tabRepo=CS2113-AY1819S2-T09-2_main_master[Functional code]] [https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=&sort=displayName&since=2019-02-10&until=2019-04-01&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false&tabAuthor=BrittonAlone&tabRepo=CS2113-AY1819S2-T09-2_main_master[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` on GitHub
** Enhancements to existing features:
*** Updated the GUI for reminder.
*** Wrote additional tests for existing features.
** Documentation:
*** Did improvement to UserGuide according to new features.
*** Did improvement to DeveloperGuide according to new features
** Community:
*** PRs reviewed.
*** The filterlist() function of the new list commands I added was adopted by my teammates.


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

=== Listing all tasks : `list`/`l`

Shows a list of tasks in Tasketch.

Format:

* `list` +
Lists all the tasks of today +

* `list DATE` +
Lists all the tasks of that specific date +

Examples:

* `list 02-2019` +
Lists all the tasks in February, 2019
* `list 20-02-2019` +
Lists all the tasks in February 20th, 2019
* `list` +
Lists all the tasks in the storage

=== Reminding the users of the nearest task : `remind`

Shows to the user the nearest tasks of certain category. +

Format:

* `remind start` +
Reminds the users of most recently begin tasks of all categories. +

* `remind ddl` +
Remind the users of most recent deadline of all categories. +

* `remind a/e/c/r/o ddl/start` +
Remind the users of most recent start tasks or deadline of specified category.

****
* "a" - Academic +
* "e" - Entertainment +
* "c" - Co-Curricular Activity (CCA) +
* "r" - Errand +
* "o" - Other
****

Examples:

* `remind e start` +
Shows a list of nearest start tasks of "entertainment" category.



== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

//include::../DeveloperGuide.adoc[tag=undoredo]

//include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
