= Zhang Jingchen - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Tasketch

---

== Overview

Tasketch is for those who need to manage their time by allocating time for each daily task. More importantly, Tasketch is optimized for those who prefer to use a desktop app and work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI). +
This Project Portfolio is to indicate what I have done to enhance the functionality of this project.

== Summary of contributions

* *Major enhancement*: Enhance visual feedback with timeline feature.
** What it does: It helps the user to visually view the time they should spend on each task.
** Justification: This feature improves the product significantly because people tend to believe what they see, it is good to have a vivid picture of the whole timeline.
** Highlights: This feature helps the user to better manage their tasks and decide on time allocation.
** Credits: _{Shibo's idea is used on filtering the desired tasks on a specific date so that I can display the tasks according to different categories on the timeline}_

* *Minor enhancement*: morphed the find and history command that allows the user to easily locate a task and see history commands.

* *Code contributed*: [https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=Jingchen&sort=displayName&since=2019-02-10&until=2019-04-01&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false&tabAuthor=jingchen-z&tabRepo=CS2113-AY1819S2-T09-2_main_master&repoSort=true[Functional code]] [https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=&sort=displayName&since=2019-02-10&until=2019-04-01&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false&tabAuthor=jingchen-z&tabRepo=CS2113-AY1819S2-T09-2_main_master[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** The UI designer and the person in charge of group work coordination.
*** Managed releases `v1.0` - `v1.4` (2 releases) on GitHub
** Enhancements to existing features:
*** Improved the GUI structure.
*** Updated the GUI arrangement and corresponding enhancing features (Pull requests https://github.com/CS2113-AY1819S2-T09-2/main/pull/83[#83], https://github.com/CS2113-AY1819S2-T09-2/main/pull/91[#91], https://github.com/CS2113-AY1819S2-T09-2/main/pull/96[#96])
*** Updated previous commands (Pull requests https://github.com/CS2113-AY1819S2-T09-2/main/pull/51[#51], https://github.com/CS2113-AY1819S2-T09-2/main/pull/45[#45])
** Documentation:
*** Updated UserGuide and DeveloperGuide. (available https://github.com/jingchen-z/main/blob/master/docs/UserGuide.adoc[UserGuide] https://github.com/jingchen-z/main/blob/master/docs/DeveloperGuide.adoc[DeveloperGuide])
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Some parts of the history feature I added was referenced by several other class mates (https://github.com[1], https://github.com[2])
*** My UI structure and design are referenced.

** Tools:
*** Google is always the best friend. :)
*** Java, Javafx and IntelliJ.


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

=== Update the project picture

The overview and screen shoot picture (available https://github.com/CS2113-AY1819S2-T09-2/main/blob/master/docs/images/Ui.png[[picture]])

=== Set the calendar to desired month : `month`

Shows the desired month to the user. Noted that only previous month and next month will be shown. +
e.g. Current month is April, then only March and May can be shown.

[TIP]
The feature for changing the background color of each day on the calendar will come in v2.0!

Format:

* `month +` +
Changes the current calendar to next month. +

* `month -` +
Changes the current calendar to previous month.

=== Shows the timeline of a specific day to the user : `timeline` +

* `timeline` +
Shows the timeline of today by default. +

* `timeline [DATE]` +
Shows the timeline of that date. +

[WARNING]
After adding or editing a task, user needs to retype timeline [DATE] to refresh the timeline. +
This implementation is to make sure this feature is not purely part of UI.


Examples:


* `timeline` +
Shows the timeline for today.

* `timeline 01-04-19` +
Shows the whole timeline for 1st April 2019.

=== Searching tasks by keywords: `find`/`f`

Finds tasks whose topic or description contain any of the given keywords.

Format: `search KEYWORD [MORE_KEYWORDS] ...`

****
* The search is case insensitive. e.g `Tutorial` will match `tutorial`.
* The order of the keywords does not matter. e.g. `CS2113T tutorial` will match `tutorial CS2113T`.
* Only the description is searched.
* Only full words will be matched e.g. `tut` will not match `tutorial`.
* Tasks matching at least one keyword will be returned (i.e. `OR` search). e.g. `CS2113T tutorial` will return `CS2113T lecture`, `CS3235 tutorial`.
****

Examples:

* `find CS2113T` +
Returns `CS2113T lecture`
* `f Lecture` +
Returns `CS2113T lecture` and `CS3235 lecture`

=== Deleting a task : `delete`/`d`

Deletes the specified task from Tasketch.

Format: `delete INDEX_NUMBER`

****
* Each tasks is identified by the index number shown in the task list.
* Deletes the task with the index number.
****

Examples:

* `list` +
`delete 1` +
Deletes the task with index number 1 in task list.
* `find cs2113t` +
`delete 1` +
Deletes the task with index number 1 in task list.


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
=== Effective Visualization feature

==== Current Implementation
There are mainly two parts in this features, **calendar** and **timeline arrangement**

These two parts will help the user better arrange their time usage by visualization of time.

* **There are currently two commands with parameters to help achieve this, `month` and `timeline`.**

** **Implementation for Calendar: ** Using `GridPane` to separate the whole calendar area into 35 grids.

*** Each one of the 35 grids is filled with PaneNode which is defined as area for a day.
*** PaneNode extends AnchorPane.

***

** **Implementation for Timeline:** Using javafx and segment each part of the browserPanel.

*** First, separate the whole `browserPanel` into 2 parts: `upperPane` and `timelinePane`.
*** Second, separate the `upperPane` into `calendarPane` and `reminderPane`.
*** The whole implementation of `timeline` is in `timelinePane` using javafx.
*** The overall structure is javafx VBox, which is a vertical arrangement structure.
*** Inside the VBox, there are key time points for interval of 2 hours. Then the timeline for each category.

// end::Effective Visualization[]

//include::../DeveloperGuide.adoc[tag=undoredo]

//include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
