= Zeyang Li - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Tasketch

---

== Overview

Tasketch is an application that helps you to manage your everyday time by giving you an overview of all the time planned
for all the tasks in a daily manner. It also helps you to be aware of all the tasks dateline too.

== Summary of contributions

* *Major enhancement*: +
   1. Added the ability to clear tasks which start from one specific date or month and also clear all tasks that are finished before today. +
   2. Added the ability to give users suggestion when they type the command words wrongly. +
   3. Still working on the import and export feature.
** What it does: +
    a. It allows the user to clear some tasks that are no longer needed on the daily basis or the monthly basis or even clear all finished tasks in the storage. +
    b. It is more user friendly because the system will be smart to guess what is the most similar command with the wrongly typed command word. +
    c. It will also allow the users to import or export the tasks in Json file.
** Justification: +
    This feature improves the product significantly because a user can make clear a branch of tasks in the app. And when users have forgot or typed wrongly a command word, it will give suggestions to them. Also, it allows the app to be able to linked with the outside files.
** Highlights: +
    This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: +
    Codes and ideas related are inspired by https://github.com/CS2113-AY1819S1-W12-1/main[CS2113-AY1819S1-W12-1]


* *Minor enhancement*: +
 Changed a bit of the ability to open help window, to exit the program and to undo and redo the previous command.

* *Code contributed*: [https://github.com/CS2113-AY1819S2-T09-2/main/tree/master/src/main/java/seedu/address/export[Export code]] [https://github.com/CS2113-AY1819S2-T09-2/main/tree/master/src/main/java/seedu/address/commons/events[Events code]][https://github.com/CS2113-AY1819S2-T09-2/main/tree/master/src/main/java/seedu/address/logic/suggestions[Suggestion code]][https://github.com/CS2113-AY1819S2-T09-2/main/blob/master/src/main/java/seedu/address/logic/parser/ClearCommandParser.java[Clear Command Parser]][https://github.com/CS2113-AY1819S2-T09-2/main/blob/master/src/main/java/seedu/address/logic/commands/ClearCommand.java[Clear Command]][https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=&sort=displayName&since=2019-02-10&until=2019-04-01&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false&tabAuthor=Zeyang-Li&tabRepo=CS2113-AY1819S2-T09-2_main_master[RepoSence Report]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.3` (2 releases) on GitHub
** Enhancements to existing features:
*** Updated the clear command (Pull requests https://github.com[#33], https://github.com[#34])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide, developer guide, Readme: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#28], https://github.com[#31], https://github.com[#32], https://github.com[#35], https://github.com[#52], https://github.com[#58], https://github.com[#65]
*** Contributed to forum discussions (examples:  https://github.com[])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the input suggestion feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** bring in a third party library (opencsv) to the project (https://github.com[#42])



== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

==== Clearing all tasks : `clear`/`c`

If you have done with the tasks, simply clear them from the Tasketch, so that they will not disrupt your time planning.

Format:

* `clear` +
Clears all the tasks in Tasketch

* `clear DATE` +
Clears all the tasks starting from the specified date

Examples:

* `clear 21-02-2019` +
Clears all the tasks which start from February 21st, 2019.
* `clear 02-2019` +
Clears all the tasks which start from February, 2019.
* `clear before` +
Clears all the tasks which finished before today.
* `clear` +
Clears all the tasks in the storage.

Result: +
The tasks of your date choice should be cleared from the task list on the left of the app. +
The correspond time duration for those tasks will be deducted from the Daily Time Planner.


=== Import/Export
This feature allows you to import an existing json file which contains your other tasks in Tasketch. Also, it supports
the product to export what you have in the Tasketch to a json file if you want.


=== Export tasks displayed: `export`
You can save all tasks or filtered tasks into a json file. It can be used with `list` or `find`. +
Format: `export FILENAME.json [CATEGORY]`

Examples:

* `find Revise` +
  `export revise.json` +
   Exports all tasks which are named with keyword "Revise" in revise.json.
* `export academic.json a` +
   Exports all academic tasks into academic.json.
* `list 13-03-19` +
  `export 13-03-19.json` +
   Exports all tasks which starts on March 13, 2019 in 13-03-19.json.
*  `export Tasketch.json` +
   Exports all tasks which are shown on the left list in Tasketch.json.

[NOTE]
====
1.  The file will be located in `<DIRECTORY OF YOUR JAR FILE>/data/FILENAME.json`
2.  This command overwrites any files with the same name at `<DIRECTORY OF YOUR JAR FILE>/data/`
3.  If you export tasks based on categories, the left list will also change to show all tasks which are exported.
====


==== Import tasks: `import`
If you have a classmate who have the same module with you, and you forget to add any related
task into Tasketch. There are a brunch of tasks in this module. In this case, you do not
need to add them one by one. Instead, you can simply ask your friend to export all tasks about this module and send the
file to you. What you have to do is just simply import it.

Format: `import FILENAME.json`

Examples:

* `import revise.json` +
   Imports all tasks in revise.json into Tasketch.

[NOTE]
====
1.  The file to import must be placed in `<DIRECTORY OF YOUR JAR FILE>/data/`
2.  Tasks that already exist in your Tasketch won’t be imported. To import an existing task in Tasketch with different details, please `delete` it first.
====

=== Versioned Tasketch
This feature will help you to check all the commands you have typed into Tasketch. Besides, it gives you a chance to
regret your previous attempts when playing with Tasketch.

==== Listing entered commands : `history`/`h`

Lists all the commands that you have entered in reverse chronological order. +

Format: `history`

==== Undoing previous command : `undo`/`u`

Restores the Tasetch to the state before the previous undoable command was executed. +

Format: `undo`

Examples:

* `delete 1` +
  `list` +
  `undo` (reverses the `delete 1` command)
* `delete 1` +
  `clear` +
  `undo`  (reverses the `delete 1` command) +
  `undo` (reverses the `clear` command)


==== Redoing the previously undone command : `redo`/`r`

Reverses the most recent `undo` command. +

Format: `redo`

Examples:

* `delete 1` +
  `undo` (reverses the `delete 1` command) +
  `redo` (reapplies the `delete 1` command)
* `delete 1` +
  `redo` +
   The `redo` command fails as there are no undo commands executed previously.
* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +
`redo` (reapplies the `clear` command)


=== Viewing help : `help`

In case you are clueless, you can always use this command get help on all the commands available and their functions.

Format: `help`

=== Exiting the program : `exit`

If you are done using the app, you just use this command to exit and close the app.

Format: `exit`


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

// tag::suggestiom[]
=== Suggestion feature

The suggestions feature gives users helpful suggestions on what command to type, and corrections for commands when incorrect commands are being entered.

==== Current Implementation

There are two kind of suggestions supported by this feature.

Firstly, when a user has typed part of the command word and he forgets what is the whole correct command word, and then presses TAB. The system will suggest commands based on the current prefix string. If this command have parameters and the user types TAB again, the system will also suggest all the parameters about this command.

Secondly, when a user completes entering a command (after pressing ENTER key), if the command typed is invalid, the system will suggest a similar command based on the edit distance (which will be explained later).

**Wrong Command Suggestion**

Given below is an example usage of how the WrongCommandSuggestion behaves at each step.

*Step 1*: The user would type in the command string wrongly.

*Step 2*: The command would be parsed into the TaskBookParser class. Since no commands match the word exactly, it would fall into the default case.

*Step 3*: The default case would extract out only the command portion of the user input, and input it into the WrongCommandSuggestion class.

*Step 4*: WrongCommandSuggestion would first check the alphabets occurrence in the command word typed by users, if there is any correct command word has the same alphabets occurrence, WrongCommandSuggestion will return this command word immediately.

*Step 5*: Otherwise, WrongCommandSuggestion then would then instantiate the StringSimilarity class to find the nearest match of a word.

*Step 6*: editDistance in StringSimliarity class would be called to find out the edit distance between two words. These two words would be the wrong command the user has input, and the list of available commands in the whole application.

*Step 7*: WrongCommandSuggestion would then compare if the edit distance of the current command is shorter than the current shortest edit distance command (which is initialised to 3 edits). If it is shorter, it would then suggest the current command.

*Step 8*: WrongCommandSuggestion would then return the suggestion in a string, which would then be inputted into the CommandException, to be thrown to the LogicManager class.

==== Design Considerations

===== For the WrongCommandSuggestion implementation

* **Alternative 1:** Compare the input command and the actual command character by character and see which command has the most matches.
** Pros: Easy to implement.
** Cons: Not as accurate or reliable in terms of giving a correct match of command.
* **Alternative 2:** Use a string matching algorithm to implement the matching and difference calculation between the command and the user input.
** Pros: Accurate prediction or suggestions from actual commands.
** Cons: Difficult to implement, and might require more processing overhead.
* **Alternative 3(current choice):** Combination of the two.
** Pros: More accurate prediction.
** Cons: More difficult to implement.
// end::suggestion[]

// tag::import/export[]
=== Import/Export feature

==== Current Implementation

===== Import
This operation is exposed in the Model interface as Model#importTaskBook().

Given below is an example usage scenario and how the export mechanism behaves at each step.

*Step 1*: The user calls the import command.

*Step 2*: The LogicManager calls parseCommand with the user input.

*Step 3*: The TaskBookParser is called and it returns a ImportCommand object to LogicManager.

*Step 4*: The LogicManager calls execute() on the ImportCommand object

*Step 5*: The Logic component then interacts with the Model component by calling importTasksFromTaskBook() of the Model interface.

*Step 6*: The Model interface creates a new Import object and then pass the filePath to the ImportManager.

*Step 7*: The Import object will call JsonFileStorage class to loadDataFromSaveFile.

*Step 8*: The ImportManager class will call JsonFileStorage class to saveDataToFile.

*Step 9*: The JsonFileStorage class will call JsonUtil class to fromJsonString.

*Step 10*: The ModelManager will get a ReadOnlyTaskBook object and then it will addTasksToTaskBook.

*Step 11*: If there is any new task added, the ModelManager will updateFilteredTaskList.

===== Export

This operation is exposed in the Model interface as Model#exportTaskBook().

Given below is an example usage scenario and how the export mechanism behaves at each step.

*Step 1*: The user calls the export command.

*Step 2*: The LogicManager calls parseCommand with the user input.

*Step 3*: The TaskBookParser is called and it returns a ExportCommand object to LogicManager.

*Step 4*: The LogicManager calls execute() on the ExportCommand object

*Step 5*: The Logic component then interacts with the Model component by calling exportFilteredTaskBook() of the Model interface.

*Step 6*: The Model interface creates a new Export object and then pass the filteredTaskList and the filePath to the ExportManager.

*Step 7*: The Export object calls saveFilteredTasks function.

*Step 8*: The ExportManager class will call JsonFileStorage class to saveDataToFile.

*Step 9*: The JsonFileStorage class will call JsonUtil class to saveJsonFile.

*Step 10*: The JsonUtil class will call FileUtil class to writeToFile.

*Step 11*: The FileUtil class will finally call File class to write.

==== Design Considerations
// to be added

// end::import/export[]


== PROJECT: Tasketch

