= Zeyang Li - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Tasketch

---

== Overview

Tasketch is an application that helps you to manage your everyday time by giving you an overview of all the time planned
for all the tasks in a daily manner. It also helps you to be aware of all the tasks dateline too.

== Summary of contributions

* *Major enhancement*: +
   1. Added the ability to clear tasks which start from one specific date or month and also clear all tasks that are finished before today. +
   2. Added the ability to give users suggestion when they type the command words wrongly. +
   3. Still working on the import and export feature.
** What it does: +
    a. It allows the user to clear some tasks that are no longer needed on the daily basis or the monthly basis or even clear all finished tasks in the storage. +
    b. It is more user friendly because the system will be smart to guess what is the most similar command with the wrongly typed command word. +
    c. It will also allow the users to import or export the tasks in Json file.
** Justification: +
    This feature improves the product significantly because a user can make clear a branch of tasks in the app. And when users have forgot or typed wrongly a command word, it will give suggestions to them. Also, it allows the app to be able to linked with the outside files.
** Highlights: +
    This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: +
 _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: +
 Changed a bit of the ability to open help window, to exit the program and to undo and redo the previous command.

* *Code contributed*: [https://github.com/CS2113-AY1819S2-T09-2/main/tree/master/src/main/java/seedu/address/export[Export code]] [https://github.com/CS2113-AY1819S2-T09-2/main/tree/master/src/main/java/seedu/address/commons/events[Events code]][https://github.com/CS2113-AY1819S2-T09-2/main/tree/master/src/main/java/seedu/address/logic/suggestions[Suggestion code]][https://github.com/CS2113-AY1819S2-T09-2/main/blob/master/src/main/java/seedu/address/logic/parser/ClearCommandParser.java[Clear Command Parser]][https://github.com/CS2113-AY1819S2-T09-2/main/blob/master/src/main/java/seedu/address/logic/commands/ClearCommand.java[Clear Command]][https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=&sort=displayName&since=2019-02-10&until=2019-04-01&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false&tabAuthor=Zeyang-Li&tabRepo=CS2113-AY1819S2-T09-2_main_master[RepoSence Report]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.3` (2 releases) on GitHub
** Enhancements to existing features:
*** Updated the clear command (Pull requests https://github.com[#33], https://github.com[#34])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide, developer guide, Readme: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#28], https://github.com[#31], https://github.com[#32], https://github.com[#35], https://github.com[#52], https://github.com[#58], https://github.com[#65]
*** Contributed to forum discussions (examples:  https://github.com[])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the input suggestion feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** bring in a third party library (opencsv) to the project (https://github.com[#42])



== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

===== Clearing all tasks : `clear`/`c`

If you have done with the tasks, simply clear them from the Tasketch, so that they will not disrupt your time planning.

Format:

* `clear` +
Clears all the tasks in Tasketch

* `clear DATE` +
Clears all the tasks starting from the specified date

Examples:

* `clear 21-02-2019` +
Clears all the tasks which start from February 21st, 2019.
* `clear 02-2019` +
Clears all the tasks which start from February, 2019.
* `clear before` +
Clears all the tasks which finished before today.
* `clear` +
Clears all the tasks in the storage.

Result: +
The tasks of your date choice should be cleared from the task list on the left of the app. +
The correspond time duration for those tasks will be deducted from the Daily Time Planner.

==== Undoing previous command : `undo`/`u`

Restores the Tasetch to the state before the previous undoable command was executed. +

Format: `undo`

Examples:

* `delete 1` +
  `list` +
  `undo` (reverses the `delete 1` command)
* `delete 1` +
  `clear` +
  `undo`  (reverses the `delete 1` command) +
  `undo` (reverses the `clear` command)


==== Redoing the previously undone command : `redo`/`r`

Reverses the most recent `undo` command. +

Format: `redo`

Examples:

* `delete 1` +
  `undo` (reverses the `delete 1` command) +
  `redo` (reapplies the `delete 1` command)
* `delete 1` +
  `redo` +
   The `redo` command fails as there are no undo commands executed previously.
* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +
`redo` (reapplies the `clear` command)

==== Getting wrong command suggestions
There so many commands in the app, so to help you to use the app easier, it will tell you what you have typed wrongly automatically,
by giving a list of closest approximations of word through the message box after pressing `enter`. +

****
* The input is not case sensitive, hence it would increase the chance of getting a closer approximation of the correct command!
* This feature tolerates a maximum of two wrong alphabets.
* This feature allows user to type in a command which has the same alphabets with one of the correct command word but in different order. The system can give suggestion even if the user type in the reverse command word.
****

Examples：

* If you want to type `clear` but typed `clarr` instead, the system will tell you that it is an unknown command, and would suggest the command `clear` instead.
* If you want to type `exit` but typed `ecot` instead, the system will tell you that it is an unknown command, and would suggest the command `exit` and `edit` instead.
* If you want to type `history` but typed `hsitryo` instead, the system will tell you that it is an unknown command, and would suggest the command `history` instead.

==== Viewing help : `help`

In case you are clueless, you can always use this command get help on all the commands available and their functions.

Format: `help`

==== Exiting the program : `exit`

If you are done using the app, you just use this command to exit and close the app.

Format: `exit`


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===



== PROJECT: Tasketch

